### ISSUE TITLE
quality not supported

### ISSUE THREAD

**Issue by Fr-Dae** [harag-on-steam/factorio-naked-rails-f2#1]
if for no reason, you make quality rail and convert it with your tool, it's desable quaility and turn it intro normal rail.

in addition if you make ctrl z,(cncel) you erase the rail )

**Comment by harag-on-steam** [comment]
both fixed in 1.0.1

**Comment by Fr-Dae** [comment]
you don't link this issue to a PR ?

**Comment by harag-on-steam** [comment]
Fixed in 5b612683d37ab4e31a ;-)

**Comment by Fr-Dae** [comment]
it's a commit not a PR, technicly you should make 
issue link to a branch
and this branch make a PR (link to issue)
when you merge, the issue it's autoclose and you have nice an clean release update and easy review code

**Comment by harag-on-steam** [comment]
I could. But I won't. Thanks for the report.
